services:
  # PostgreSQL 17 Database
  postgres:
    image: postgres:17-alpine
    container_name: magwebapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: magwebapp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - magwebapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d magwebapp_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: magwebapp-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - magwebapp-network

volumes:
  postgres_data:
    name: magwebapp_postgres_data
  pgadmin_data:
    name: magwebapp_pgadmin_data

networks:
  magwebapp-network:
    name: magwebapp-network
    driver: bridge